// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtaAxURJI6HR_fx3LGz8i_yPQCr0KF5iQ',
    appId: '1:876558489779:web:506330181ff35fae6db8c6',
    messagingSenderId: '876558489779',
    projectId: 'campusoverflow-d5240',
    authDomain: 'campusoverflow-d5240.firebaseapp.com',
    storageBucket: 'campusoverflow-d5240.appspot.com',
    measurementId: 'G-4BH3R79VGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmwcr6tTJg312yY2iLzYHXHKNKM2FjLkU',
    appId: '1:876558489779:android:07833806c4d9779a6db8c6',
    messagingSenderId: '876558489779',
    projectId: 'campusoverflow-d5240',
    storageBucket: 'campusoverflow-d5240.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtaAxURJI6HR_fx3LGz8i_yPQCr0KF5iQ',
    appId: '1:876558489779:web:6e4de347246d32a66db8c6',
    messagingSenderId: '876558489779',
    projectId: 'campusoverflow-d5240',
    authDomain: 'campusoverflow-d5240.firebaseapp.com',
    storageBucket: 'campusoverflow-d5240.appspot.com',
    measurementId: 'G-T2PV7538XP',
  );
}
